// ── Data: 33 Denominaciones Cristianas ──
// Usado por app.js para renderizar la tabla y los modales.

const DENOMINACIONES = [
  {
    year: 33, name: "Iglesia Primitiva / Iglesia Católica (origen)", region: "Medio Oriente",
    familia: "Católica",
    doctrinas: "Trinidad, Encarnación, 7 Sacramentos, Autoridad papal, Tradición apostólica",
    t1: "Trinidad, Cristología, Justificación por fe",
    t2: "Magisterio papal, Sucesión apostólica, 7 sacramentos",
    t3: "Indulgencias, Mariología, Devoción a santos",
    gobierno: "Papal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "73 libros", spread: "Mundial",
    nota: "Infalibilidad papal (1870); única Iglesia verdadera según Roma",
    obs: "Fundada por Jesucristo según la fe católica; el Papa como Vicario de Cristo.",
    nonOrthodox: false
  },
  {
    year: 325, name: "Iglesia Ortodoxa Oriental (consolidación)", region: "Constantinopla",
    familia: "Ortodoxa",
    doctrinas: "Trinidad, Theosis, Concilios ecuménicos, Iconografía, Tradición sagrada",
    t1: "Trinidad, Theosis (deificación), Concilios ecuménicos",
    t2: "Iconografía, Hesicasmo, sin Filioque",
    t3: "Jurisdicciones nacionales autocéfalas",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "~76 libros", spread: "Europa del Este · Medio Oriente",
    nota: "El Filioque es error teológico; autocefalia de cada patriarcado",
    obs: "La Tradición Sagrada tiene autoridad coextensa con la Escritura.",
    nonOrthodox: false
  },
  {
    year: 451, name: "Iglesia Copta Ortodoxa", region: "Egipto",
    familia: "Ortodoxa",
    doctrinas: "Miafisismo, Cristología de Cirilo, Tradición alejandrina, Ascetismo",
    t1: "Cristología (miafisismo = una naturaleza), Trinidad",
    t2: "Sacramentos coptos, Ayuno intensivo",
    t3: "Prácticas litúrgicas en copta antiguo",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "~81 libros", spread: "Egipto · África · Diáspora",
    nota: "Rechaza el Concilio de Calcedonia (451); profundas raíces ascéticas",
    obs: "La línea monofisita se divide en Copto, Etíope, Armenio e Indio.",
    nonOrthodox: false
  },
  {
    year: 451, name: "Iglesia Apostólica Armenia", region: "Armenia",
    familia: "Ortodoxa",
    doctrinas: "Miafisismo, Primera nación cristiana, Liturgia armenia, Identidad nacional-religiosa",
    t1: "Cristología, Trinidad, Resurrección",
    t2: "Sacramentos, Liturgia en armenio clásico",
    t3: "Identidad étnico-religiosa armenia",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "~74 libros", spread: "Armenia · Diáspora global",
    nota: "Iglesia nacional de Armenia desde 301 d.C.",
    obs: "Armenia fue la primera nación en adoptar el cristianismo oficialmente.",
    nonOrthodox: false
  },
  {
    year: 1054, name: "Iglesia Ortodoxa Griega (Gran Cisma)", region: "Grecia / Bizancio",
    familia: "Ortodoxa",
    doctrinas: "Separación de Roma, Patriarcas iguales, Sin papa, Teología apofática",
    t1: "Trinidad, Cristología según los 7 concilios",
    t2: "Filioque negado, Concilios ecuménicos, Theosis",
    t3: "Liturgia Divina de Juan Crisóstomo",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "~76 libros", spread: "Grecia · Chipre · Diáspora",
    nota: "El Gran Cisma (1054) formaliza la separación Oriente–Occidente",
    obs: "El Filioque ('y del Hijo') es el núcleo teológico de la ruptura con Roma.",
    nonOrthodox: false
  },
  {
    year: 1517, name: "Iglesia Luterana", region: "Alemania",
    familia: "Luterana",
    doctrinas: "Sola Scriptura, Sola Fide, Sola Gratia, Sacerdocio universal, Consubstanciación",
    t1: "Justificación solo por fe, Trinidad, Autoridad de la Escritura",
    t2: "Sacramentos (bautismo y Eucaristía con presencia real)",
    t3: "Estructura litúrgica, año eclesiástico",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "66 libros", spread: "Europa · Norteamérica",
    nota: "Confesión de Augsburgo (1530); rechazo de indulgencias papales",
    obs: "Lutero difiere de Calvino en la Eucaristía: consubstanciación vs. simbolismo.",
    nonOrthodox: false
  },
  {
    year: 1534, name: "Iglesia Anglicana / Church of England", region: "Inglaterra",
    familia: "Anglicana",
    doctrinas: "Vía media, Episcopado histórico apostólico, 39 Artículos de Religión, Book of Common Prayer",
    t1: "Trinidad, Cristología, Justificación por fe",
    t2: "Episcopado histórico, Sacramentos (bautismo y Cena)",
    t3: "Ordenación femenina y homosexualidad (debate actual)",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Diverso",
    canon: "66 libros", spread: "Comunión anglicana mundial (165 países)",
    nota: "39 Artículos de Religión; Book of Common Prayer (1662)",
    obs: "Teología intencionalmente amplia para incluir evangélicos, anglocatólicos y liberales.",
    nonOrthodox: false
  },
  {
    year: 1536, name: "Iglesia Reformada / Presbiteriana", region: "Suiza / Ginebra",
    familia: "Reformada",
    doctrinas: "TULIP (5 puntos de Calvino), Pacto de gracia, Soberanía de Dios, Regla normativa",
    t1: "Trinidad, Predestinación soberana, Justificación solo por fe",
    t2: "Sacramentos, Teología del pacto, Gobierno presbiteriano",
    t3: "Regla normativa de adoración",
    gobierno: "Presbiteriano", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "66 libros", spread: "Global (Escocia · Corea · EE.UU.)",
    nota: "Confesión de Westminster (1647); consistorio, presbiterio y sínodo",
    obs: "TULIP: Total depravación · Elección incondicional · Expiación limitada · Gracia irresistible · Perseverancia.",
    nonOrthodox: false
  },
  {
    year: 1525, name: "Iglesia Menonita / Anabautista", region: "Suiza / Alemania",
    familia: "Anabautista",
    doctrinas: "Bautismo de creyentes, Pacifismo radical, Separación Iglesia-Estado, Comunidad de discípulos",
    t1: "Trinidad, Seguimiento de Cristo (Nachfolge), Resurrección",
    t2: "Bautismo de creyentes adultos, No violencia absoluta",
    t3: "Separación del mundo, sencillez de vida",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Diverso",
    canon: "66 libros", spread: "Norteamérica · Latinoamérica",
    nota: "Schleitheim Confession (1527); énfasis en paz y no violencia",
    obs: "La Iglesia no debe recurrir a la espada ni al Estado para su protección.",
    nonOrthodox: false
  },
  {
    year: 1693, name: "Iglesia Amish", region: "Suiza / Alsacia",
    familia: "Anabautista",
    doctrinas: "Gelassenheit (sumisión comunitaria), Separación tecnológica, Disciplina de la Ordnung, Pacifismo",
    t1: "Trinidad, Seguimiento de Cristo, Resurrección corporal",
    t2: "Bautismo de creyentes, Ordnung comunitaria vinculante",
    t3: "Separación tecnológica, vestimenta sencilla",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "66 libros", spread: "EE.UU. (Pennsylvania · Ohio)",
    nota: "Escisión menonita liderada por Jakob Ammann",
    obs: "Gelassenheit = renuncia al yo en favor de la comunidad de fe.",
    nonOrthodox: false
  },
  {
    year: 1609, name: "Iglesia Bautista", region: "Ámsterdam / Inglaterra",
    familia: "Bautista",
    doctrinas: "Bautismo de creyentes por inmersión, Congregacionalismo, Libertad religiosa, Sola Scriptura",
    t1: "Trinidad, Justificación por fe sola, Resurrección",
    t2: "Bautismo de creyentes (inmersión), Iglesia local autónoma",
    t3: "Libertad de conciencia, sin credos obligatorios",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Diverso",
    canon: "66 libros", spread: "Global",
    nota: "Confesión de Londres (1689); diversidad entre Particular (calvinista) y General (arminiana)",
    obs: "Libertad de conciencia: cada congregación es autónoma ante Dios.",
    nonOrthodox: false
  },
  {
    year: 1739, name: "Iglesia Metodista", region: "Inglaterra",
    familia: "Metodista",
    doctrinas: "Gracia preveniente, Entera santificación, Libre albedrío, Arminianismo wesleyano",
    t1: "Trinidad, Salvación por gracia mediante fe, Santificación",
    t2: "Entera santificación, Medios de gracia (oración, ayuno, comunión)",
    t3: "Estructura de circuito, cuadrilátero wesleyano",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Posmilenialismo",
    canon: "66 libros", spread: "Global",
    nota: "John Wesley; cuadrilátero: Escritura, Tradición, Razón, Experiencia",
    obs: "El metodismo generó el movimiento de Santidad, nazarenos y el pentecostalismo.",
    nonOrthodox: false
  },
  {
    year: 1747, name: "Iglesia Morava (Hermanos Moravos)", region: "Moravia / Bohemia",
    familia: "Luterana",
    doctrinas: "Unidad en lo esencial, Piedad personal, Misiones globales pioneras, Ecumenismo temprano",
    t1: "Trinidad, Cruz de Cristo como centro de la fe",
    t2: "Comunidad, Misiones interculturales",
    t3: "Liturgia y himnología característica",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "66 libros", spread: "Europa · Caribe · África",
    nota: "Primer gran movimiento misionero protestante de la historia",
    obs: "Influyeron decisivamente en John Wesley y el movimiento metodista.",
    nonOrthodox: false
  },
  {
    year: 1650, name: "Sociedad de Amigos (Cuáqueros)", region: "Inglaterra",
    familia: "Cuáquera",
    doctrinas: "Luz interior del Cristo, Sin sacramentos ni credos, Pacifismo, Igualdad radical, Sin clero",
    t1: "Luz de Cristo interior como fuente de verdad, Ética del amor",
    t2: "Sin sacramentos formales, Sin credos obligatorios",
    t3: "Pacifismo absoluto, reuniones de silencio",
    gobierno: "Sin estructura formal", bautismo: "No practicado", escato: "Diverso",
    canon: "No normativo", spread: "EE.UU. · Reino Unido",
    nota: "George Fox; ausencia total de sacramentos, liturgia y clero",
    obs: "La Luz Interior puede superar a la Escritura en su epistemología.",
    nonOrthodox: false
  },
  {
    year: 1870, name: "Testigos de Jehová", region: "EE.UU.",
    familia: "No trinitaria",
    doctrinas: "Arrianismo moderno (Jesús = ser creado), Alma mortal, 144.000, Rechazo de Cruz y transfusiones",
    t1: "Jehová como único Dios verdadero (rechazan Trinidad ortodoxa)",
    t2: "Alma mortal, Resurrección física, Rechazo de transfusiones",
    t3: "Rechazo de fiestas, autonomía del Cuerpo Gobernante",
    gobierno: "Teocrático (Cuerpo Gobernante)", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "NWT (traducción propia)", spread: "Global",
    nota: "Charles T. Russell / Rutherford; Watchtower Society",
    obs: "⚠ No es cristiano trinitario ortodoxo — rechaza la Trinidad y la deidad plena de Cristo.",
    nonOrthodox: true
  },
  {
    year: 1830, name: "Iglesia SUD (Mormones)", region: "EE.UU.",
    familia: "No trinitaria",
    doctrinas: "Restauración, Escrituras adicionales, Politeísmo social, Exaltación, Presidente-profeta vivo",
    t1: "Exaltación humana (llegar a ser dioses), Revelación continua",
    t2: "Bautismo por los muertos, Templos, Matrimonios eternos",
    t3: "Familia eterna, Leyes dietéticas (Palabra de Sabiduría)",
    gobierno: "Episcopal", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "Libro de Mormón + D&P + PGP + Biblia", spread: "Global",
    nota: "Joseph Smith; no es cristiano trinitario; doctrina de la deificación humana",
    obs: "⚠ El Dios mormón fue antes un hombre — incompatible con el teísmo cristiano clásico.",
    nonOrthodox: true
  },
  {
    year: 1568, name: "Iglesia Unitaria / Unitario Universalista", region: "Transylvania / Polonia",
    familia: "No trinitaria",
    doctrinas: "Rechazo de la Trinidad, Razón sobre revelación, Pluralismo teológico, Universalismo",
    t1: "Dios uno (anti-Trinidad), énfasis en razón y ética",
    t2: "Universalismo salvífico (todos se salvan)",
    t3: "Pluralismo: se acepta cualquier creencia",
    gobierno: "Congregacional", bautismo: "No practicado", escato: "Diverso",
    canon: "No normativo", spread: "EE.UU. · Europa",
    nota: "Faustus Socinus; muchos ya no se identifican como 'cristianos'",
    obs: "⚠ Rechazan la deidad de Cristo y la Trinidad — fuera del trinitarismo clásico.",
    nonOrthodox: true
  },
  {
    year: 1870, name: "Iglesia Adventista del Séptimo Día", region: "EE.UU.",
    familia: "Adventista",
    doctrinas: "Sábado sabático, Sueño del alma, Investigative Judgment, Segunda venida inminente, Salud holística",
    t1: "Trinidad, Segunda venida corporal, Salvación por gracia mediante fe",
    t2: "Sábado (séptimo día), Sueño del alma (estado intermedio inconsciente)",
    t3: "Dieta vegetariana, abstinencia de alcohol",
    gobierno: "Presbiteriano", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "66 libros", spread: "Global",
    nota: "Ellen G. White como 'espíritu de profecía' (don profético menor)",
    obs: "El Investigative Judgment (Juicio Investigador desde 1844) es doctrina distintiva.",
    nonOrthodox: false
  },
  {
    year: 1906, name: "Iglesia de Dios en Cristo (COGIC)", region: "EE.UU.",
    familia: "Pentecostal",
    doctrinas: "Bautismo del Espíritu Santo, Glosolalia como evidencia, Santificación, Sanidad divina",
    t1: "Trinidad, Salvación por fe, Bautismo del Espíritu Santo",
    t2: "Glosolalia como evidencia del bautismo del E.S., Sanidad divina",
    t3: "Santidad en vestimenta y conducta",
    gobierno: "Episcopal", bautismo: "Creyentes", escato: "Premilenialismo dispensacionalista",
    canon: "66 libros", spread: "EE.UU. · África · Caribe",
    nota: "Avivamiento Calle Azusa (1906); mayor denominación pentecostal negra",
    obs: "Charles Mason; énfasis en santidad y experiencia del Espíritu.",
    nonOrthodox: false
  },
  {
    year: 1914, name: "Asambleas de Dios", region: "EE.UU.",
    familia: "Pentecostal",
    doctrinas: "Bautismo del Espíritu Santo, Glosolalia, Sanidad divina, Segunda venida pronto",
    t1: "Trinidad, Salvación por fe, Bautismo del Espíritu Santo con evidencia",
    t2: "Glosolalia, Sanidad divina, Diezmo",
    t3: "Restricciones culturales (alcohol, entretenimiento mundano)",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Premilenialismo dispensacionalista",
    canon: "66 libros", spread: "Global (+200 países)",
    nota: "Declaración de Verdades Fundamentales; énfasis misional global",
    obs: "Mayor denominación pentecostal trinitaria del mundo; presente en +200 países.",
    nonOrthodox: false
  },
  {
    year: 1886, name: "Iglesia de Dios (Cleveland, TN)", region: "EE.UU.",
    familia: "Pentecostal",
    doctrinas: "Santificación, Bautismo del Espíritu Santo, Glosolalia, Sanidad divina",
    t1: "Trinidad, Justificación, Santificación entera",
    t2: "Glosolalia como evidencia, Sanidad divina",
    t3: "Vida de santidad y separación del mundo",
    gobierno: "Episcopal", bautismo: "Creyentes", escato: "Premilenialismo dispensacionalista",
    canon: "66 libros", spread: "Global",
    nota: "Una de las denominaciones pentecostales más antiguas",
    obs: "Previa al Avivamiento de Azusa; fuerte énfasis en santidad wesleyana.",
    nonOrthodox: false
  },
  {
    year: 1901, name: "Iglesia Pentecostal Unida (Unicitarios)", region: "EE.UU.",
    familia: "No trinitaria",
    doctrinas: "Modalismo (Dios es solo Jesús), Bautismo 'en el nombre de Jesús', Pentecostalismo no trinitario",
    t1: "Unicidad de Dios = solo Jesús (rechazan Trinidad como tripartita)",
    t2: "Bautismo SOLO en el nombre de Jesús",
    t3: "Santidad en vestimenta, prohibición de adornos",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "66 libros", spread: "EE.UU. · Latinoamérica",
    nota: "Rechaza la Trinidad ortodoxa; teología del 'nombre de Jesús'",
    obs: "⚠ Modalismo: el Padre, Hijo y Espíritu son modos del único Dios-Jesús.",
    nonOrthodox: true
  },
  {
    year: 1960, name: "Movimiento Carismático Católico", region: "EE.UU. (Duquesne)",
    familia: "Carismática",
    doctrinas: "Dones del Espíritu dentro del catolicismo, Glosolalia, Sanidad, Renovación espiritual",
    t1: "Trinidad, Sacramentos católicos, Autoridad papal",
    t2: "Dones del Espíritu Santo (glosolalia, profecía, sanidad)",
    t3: "Renovación de la Iglesia desde adentro",
    gobierno: "Papal", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "73 libros", spread: "Global (120 millones+)",
    nota: "Duquesne Weekend (1967); integra los carismas dentro de la estructura romana",
    obs: "El Papa Francisco ha mostrado simpatía hacia este movimiento.",
    nonOrthodox: false
  },
  {
    year: 1968, name: "Movimiento Carismático / Neo-Carismático", region: "Global",
    familia: "Carismática",
    doctrinas: "Dones actuales del Espíritu, Profecía contemporánea, Apóstoles y profetas hoy, Guerra espiritual",
    t1: "Trinidad, Salvación por gracia, Presencia activa del Espíritu",
    t2: "Dones del Espíritu, Apóstoles y profetas modernos",
    t3: "Guerra espiritual territorial, Prosperidad en algunos sectores",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Premilenialismo",
    canon: "66 libros", spread: "Global (África · Latinoamérica · Asia)",
    nota: "Diversidad enorme; incluye la 'Nueva Reforma Apostólica' (NAR)",
    obs: "Peter Wagner sistematizó la NAR; énfasis en dominación cultural y 7 montañas.",
    nonOrthodox: false
  },
  {
    year: 1980, name: "Movimiento Neopentecostal", region: "Global (EE.UU. · Brasil · Colombia · Nigeria)",
    familia: "Neopentecostal",
    doctrinas: "Teología de la Prosperidad, Confesión positiva, Guerra espiritual, Liderazgo apostólico, Unción",
    t1: "Trinidad, Salvación por fe, Bautismo del Espíritu Santo",
    t2: "Glosolalia, Sanidad divina, Apóstoles/profetas contemporáneos",
    t3: "Prosperidad material como señal de bendición divina, Pacto de sembrar y cosechar",
    gobierno: "Episcopal / Apostólico", bautismo: "Creyentes", escato: "Premilenialismo dispensacionalista",
    canon: "66 libros", spread: "Global (especialmente Latinoamérica · África · Asia)",
    nota: "K. Hagin, K. Copeland, Edir Macedo, César Castellanos; prosperidad, poder y unción",
    obs: "Se diferencia del pentecostalismo clásico por: teología de prosperidad, ausencia de ética de santidad, énfasis en éxito material. Figuras: César Castellanos y Harold Caballeros (Colombia), Edir Macedo y Silas Malafaia (Brasil), David Oyedepo (Nigeria), Joel Osteen (EE.UU.). Doctrina 'nombra y reclama' (name-it-claim-it). Muy criticado por J. MacArthur, M. Horton y otros por distorsionar el evangelio.",
    nonOrthodox: false
  },
  {
    year: 1809, name: "Iglesias de Cristo / Discípulos de Cristo", region: "EE.UU.",
    familia: "Restauracionista",
    doctrinas: "Restauración del NT, Solo la Biblia, Sin instrumentos (COFC), Unidad cristiana",
    t1: "Trinidad, Salvación, Bautismo como parte de la conversión",
    t2: "A cappella (Churches of Christ), Cena del Señor semanal",
    t3: "Autonomía congregacional total",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Premilenialismo histórico",
    canon: "66 libros", spread: "EE.UU. · Global",
    nota: "Movimiento Stone-Campbell; sin credos más allá del Nuevo Testamento",
    obs: "Barton W. Stone y Alexander Campbell; se dividen en tres ramas hoy.",
    nonOrthodox: false
  },
  {
    year: 1830, name: "Iglesia Cristiana (Discípulos de Cristo)", region: "EE.UU.",
    familia: "Restauracionista",
    doctrinas: "No credos sino el NT, Unidad cristiana, Bautismo por inmersión, Cena del Señor semanal",
    t1: "Trinidad, Salvación, Bautismo",
    t2: "Cena semanal, Unidad ecuménica",
    t3: "Diversidad teológica interna amplia",
    gobierno: "Congregacional", bautismo: "Creyentes", escato: "Diverso",
    canon: "66 libros", spread: "EE.UU.",
    nota: "Barton W. Stone & Alexander Campbell; rama más liberal del movimiento",
    obs: "Una de las tres ramas del movimiento Stone-Campbell.",
    nonOrthodox: false
  },
  {
    year: 1880, name: "Ejército de Salvación", region: "Inglaterra",
    familia: "Metodista",
    doctrinas: "Santidad wesleyana, Sin sacramentos, Servicio social como misión central, Evangelismo callejero",
    t1: "Trinidad, Salvación por gracia mediante fe",
    t2: "Santidad, Servicio social integral (pobres, adictos, sin hogar)",
    t3: "Sin sacramentos formales",
    gobierno: "Episcopal", bautismo: "No practicado", escato: "Premilenialismo",
    canon: "66 libros", spread: "Global (130+ países)",
    nota: "William Booth; sacramentos considerados no esenciales",
    obs: "Estructura militar (rangos) como metáfora de la milicia espiritual.",
    nonOrthodox: false
  },
  {
    year: 1889, name: "Iglesia del Nazareno", region: "EE.UU.",
    familia: "Metodista",
    doctrinas: "Santidad wesleyana, Segunda obra de gracia, Entera santificación, Arminianismo",
    t1: "Trinidad, Justificación, Entera santificación",
    t2: "Segunda obra de gracia, Normas de vida santa",
    t3: "Restricciones en entretenimiento y vestimenta",
    gobierno: "Episcopal", bautismo: "Infantes / adultos", escato: "Premilenialismo",
    canon: "66 libros", spread: "Global",
    nota: "Movimiento de Santidad; énfasis en perfección cristiana wesleyana",
    obs: "La entera santificación es una segunda crisis de gracia post-conversión.",
    nonOrthodox: false
  },
  {
    year: 1816, name: "Iglesia Episcopal Metodista Africana (AME)", region: "EE.UU.",
    familia: "Metodista",
    doctrinas: "Metodismo wesleyano, Justicia racial, Dignidad humana, Santificación",
    t1: "Trinidad, Salvación, Dignidad de toda persona creada a imagen de Dios",
    t2: "Santificación, Justicia social y racial",
    t3: "Herencia afroamericana como marco interpretativo",
    gobierno: "Episcopal", bautismo: "Infantes", escato: "Premilenialismo",
    canon: "66 libros", spread: "EE.UU. · África · Caribe",
    nota: "Richard Allen; primera denominación fundada por afroamericanos en EE.UU.",
    obs: "Nació como protesta contra la segregación en iglesias metodistas blancas.",
    nonOrthodox: false
  },
  {
    year: 1619, name: "Iglesia Reformada Holandesa (Dutch Reformed)", region: "Países Bajos",
    familia: "Reformada",
    doctrinas: "Calvinismo estricto, Cánones de Dort, Alianza de gracia, Catecismo de Heidelberg",
    t1: "TULIP, Predestinación, Trinidad, Justificación solo por fe",
    t2: "Sacramentos, Teología del pacto, Gobierno presbiteriano",
    t3: "Liturgia reformada, Catecismo de Heidelberg como estándar",
    gobierno: "Presbiteriano", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "66 libros", spread: "Países Bajos · Sudáfrica · EE.UU.",
    nota: "Cánones de Dort (1618-19); influencia histórica en Sudáfrica",
    obs: "Históricamente vinculada al apartheid en Sudáfrica — reconocida como hermenéutica fallida.",
    nonOrthodox: false
  },
  {
    year: 1948, name: "Iglesia Luterana-Sínodo de Missouri (LCMS)", region: "EE.UU.",
    familia: "Luterana",
    doctrinas: "Luteranismo confesional, Inerrancia bíblica, Presencia real en Eucaristía, Sin ordenación femenina",
    t1: "Trinidad, Justificación solo por fe, Inerrancia e infalibilidad de la Escritura",
    t2: "Sacramentos (presencia real en Eucaristía), Bautismo regenerador",
    t3: "Ordenación exclusivamente masculina",
    gobierno: "Presbiteriano", bautismo: "Infantes", escato: "Amilenialismo",
    canon: "66 libros", spread: "EE.UU. · Global",
    nota: "Luteranismo confesional; rechaza comunión con ELCA (luteranos liberales)",
    obs: "Alta teología sacramental; la Eucaristía es el cuerpo y sangre real de Cristo.",
    nonOrthodox: false
  }
];
